"""
Alignment protocol comparison (D0 daily vs 6h/12h/24h).

This script operationalizes the "canonical aligners" requirement from `作业要求.md`:
- D0 daily (calendar-day of ICU admission, chartdate-style)
- 6h / 12h / 24h charttime windows (anchored at ICU admission)

Note:
- Core benchmark window features (including D0) are generated by
  `code/data_processing/create_multi_window_data.py`.
- This script is a MedCAT concept-based aligner stress-test, used to isolate
  protocol effects under a fixed feature family.

We implement this comparison using MedCAT note-level concepts:
  data/processed/medcat_full/medcat_note_concepts_24h.csv
and derive windowed "has_*" binary features (and negated variants) by streaming the CSV.

Outputs:
- results/aligner_comparison/aligner_results.csv
- results/aligner_comparison/aligner_results.json
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import sys

# Ensure `code/` is importable when running as:
#   python code/baselines/train_aligner_comparison.py
sys.path.insert(0, str(Path(__file__).parent.parent))

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import average_precision_score, roc_auc_score
from sklearn.preprocessing import StandardScaler
import xgboost as xgb

from config import COHORT_FILE, N_FOLDS, PREDEFINED_SPLITS_FILE, PROCESSED_DIR, RANDOM_STATE, RESULTS_DIR
from baselines.medcat_window_features import (
    PATTERN_KEYS,
    WindowConfig,
    build_window_masks,
    masks_to_frame,
)


NOTE_CONCEPTS_FILE = PROCESSED_DIR / "medcat_full" / "medcat_note_concepts_24h.csv"

OUTPUT_DIR = RESULTS_DIR / "aligner_comparison"
OUTPUT_CSV = OUTPUT_DIR / "aligner_results.csv"
OUTPUT_JSON = OUTPUT_DIR / "aligner_results.json"

# Match the paper's data definition: keep these note types and exclude discharge notes.
ALLOWED_NOTE_TYPES = ("nursing", "radiology", "lab_comment")


def _safe_metrics(y_true: np.ndarray, y_prob: np.ndarray):
    if len(np.unique(y_true)) <= 1:
        return 0.5, float(np.mean(y_true))
    return roc_auc_score(y_true, y_prob), average_precision_score(y_true, y_prob)


def _hours_to_midnight(intime_series: pd.Series) -> np.ndarray:
    """
    Convert an ICU admission datetime into the remaining hours in that calendar day.
    D0 (chartdate-style) includes rows with chart_hour < hours_to_midnight.
    """
    dt = pd.to_datetime(intime_series, errors="coerce")
    # For NaT, default to 24h so D0 behaves like 24h rather than dropping everything.
    dt = dt.fillna(pd.Timestamp("1970-01-01T00:00:00"))
    frac = dt.dt.hour + dt.dt.minute / 60.0 + dt.dt.second / 3600.0
    cutoff = 24.0 - frac
    # Clamp to [0,24]
    cutoff = cutoff.clip(lower=0.0, upper=24.0)
    return cutoff.to_numpy(dtype=float)


def _load_base_frame() -> pd.DataFrame:
    if not COHORT_FILE.exists():
        raise FileNotFoundError(COHORT_FILE)
    if not PREDEFINED_SPLITS_FILE.exists():
        raise FileNotFoundError(PREDEFINED_SPLITS_FILE)

    cohort = pd.read_csv(COHORT_FILE)
    cohort["stay_id"] = pd.to_numeric(cohort["stay_id"], errors="coerce").astype("Int64")
    cohort["subject_id"] = pd.to_numeric(cohort["subject_id"], errors="coerce").astype("Int64")

    splits = pd.read_csv(PREDEFINED_SPLITS_FILE)
    splits["stay_id"] = pd.to_numeric(splits["stay_id"], errors="coerce").astype("Int64")
    splits["fold_id"] = pd.to_numeric(splits["fold_id"], errors="coerce").astype("Int64")

    df = cohort.merge(splits[["stay_id", "split", "fold_id"]], on="stay_id", how="inner")
    # Keep the two core tasks required by 作业要求.md
    keep_cols = [
        "stay_id",
        "subject_id",
        "intime",
        "label_mortality",
        "prolonged_los_7d",
        "split",
        "fold_id",
    ]
    missing = [c for c in keep_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in merged cohort/splits: {missing}")

    df = df[keep_cols].copy()
    df = df.dropna(subset=["stay_id", "subject_id", "split", "fold_id"])
    df["stay_id"] = df["stay_id"].astype(int)
    df["subject_id"] = df["subject_id"].astype(int)
    df["fold_id"] = df["fold_id"].astype(int)

    # Ensure labels are numeric where present (we'll drop NA per task).
    df["label_mortality"] = pd.to_numeric(df["label_mortality"], errors="coerce")
    df["prolonged_los_7d"] = pd.to_numeric(df["prolonged_los_7d"], errors="coerce")

    df["d0_cutoff_hours"] = _hours_to_midnight(df["intime"])
    return df


def _train_eval_predefined(df: pd.DataFrame, feature_cols, label_col: str, model_name: str):
    df = df.dropna(subset=[label_col]).copy()
    df[label_col] = df[label_col].astype(int)

    dev = df[df["split"] == "dev"].copy()
    test = df[df["split"] == "test"].copy()
    if len(dev) == 0 or len(test) == 0:
        raise ValueError("Split file must contain both dev and test rows")

    X_dev = dev[feature_cols].to_numpy(dtype=float)
    y_dev = dev[label_col].to_numpy(dtype=int)
    fold_dev = dev["fold_id"].to_numpy(dtype=int)

    fold_details = []
    for fold in range(1, N_FOLDS + 1):
        tr = fold_dev != fold
        va = fold_dev == fold
        if not va.any() or not tr.any():
            continue
        scaler = StandardScaler()
        X_tr = scaler.fit_transform(X_dev[tr])
        X_va = scaler.transform(X_dev[va])

        if model_name.startswith("XGBoost"):
            model = xgb.XGBClassifier(
                n_estimators=200,
                max_depth=6,
                learning_rate=0.05,
                subsample=0.9,
                colsample_bytree=0.9,
                random_state=RANDOM_STATE,
                eval_metric="logloss",
                n_jobs=-1,
            )
        else:
            model = LogisticRegression(max_iter=5000, random_state=RANDOM_STATE, n_jobs=-1)

        model.fit(X_tr, y_dev[tr])
        pred = model.predict_proba(X_va)[:, 1]
        auroc, auprc = _safe_metrics(y_dev[va], pred)
        fold_details.append({"fold": fold, "auroc": float(auroc), "auprc": float(auprc)})

    # Test: train on all dev, evaluate on holdout test
    scaler = StandardScaler()
    X_tv = scaler.fit_transform(X_dev)
    if model_name.startswith("XGBoost"):
        model = xgb.XGBClassifier(
            n_estimators=200,
            max_depth=6,
            learning_rate=0.05,
            subsample=0.9,
            colsample_bytree=0.9,
            random_state=RANDOM_STATE,
            eval_metric="logloss",
            n_jobs=-1,
        )
    else:
        model = LogisticRegression(max_iter=5000, random_state=RANDOM_STATE, n_jobs=-1)
    model.fit(X_tv, y_dev)

    X_te = test[feature_cols].to_numpy(dtype=float)
    y_te = test[label_col].to_numpy(dtype=int)
    X_te = scaler.transform(X_te)
    pred_te = model.predict_proba(X_te)[:, 1]
    test_auroc, test_auprc = _safe_metrics(y_te, pred_te)

    aurocs = [r["auroc"] for r in fold_details]
    auprcs = [r["auprc"] for r in fold_details]
    return {
        "cv_auroc_mean": float(np.mean(aurocs)) if aurocs else None,
        "cv_auroc_std": float(np.std(aurocs)) if aurocs else None,
        "cv_auprc_mean": float(np.mean(auprcs)) if auprcs else None,
        "cv_auprc_std": float(np.std(auprcs)) if auprcs else None,
        "test_auroc": float(test_auroc),
        "test_auprc": float(test_auprc),
        "fold_details": fold_details,
        "n_samples": int(len(df)),
        "positive_rate": float(np.mean(df[label_col])),
    }


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    base = _load_base_frame()
    stay_ids = base["stay_id"].to_list()
    stay_id_to_index = {sid: i for i, sid in enumerate(stay_ids)}

    windows = [
        WindowConfig(name="6h", hours=6.0),
        WindowConfig(name="12h", hours=12.0),
        WindowConfig(name="24h", hours=24.0),
        WindowConfig(name="D0", hours=None, is_d0=True),
    ]

    if not NOTE_CONCEPTS_FILE.exists():
        raise FileNotFoundError(NOTE_CONCEPTS_FILE)

    # Build masks once (covers both tasks); then train/eval per task.
    mask_by_window = build_window_masks(
        note_concepts_csv=NOTE_CONCEPTS_FILE,
        stay_id_to_index=stay_id_to_index,
        windows=windows,
        allowed_note_types=ALLOWED_NOTE_TYPES,
        d0_cutoff_hours=base["d0_cutoff_hours"].to_numpy(dtype=float),
    )

    feature_cols = PATTERN_KEYS + [f"{k}_neg" for k in PATTERN_KEYS]
    tasks = {
        "mortality": "label_mortality",
        "prolonged_los": "prolonged_los_7d",
    }
    models = ["XGBoost (MedCAT)", "LogisticRegression (MedCAT)"]

    results_rows = []
    payload = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "seed": int(RANDOM_STATE),
        "input_paths": {
            "cohort_file": str(COHORT_FILE),
            "splits_file": str(PREDEFINED_SPLITS_FILE),
            "medcat_note_concepts": str(NOTE_CONCEPTS_FILE),
        },
        "note_types_included": list(ALLOWED_NOTE_TYPES),
        "windows": [w.name for w in windows],
        "tasks": list(tasks.keys()),
        "results": [],
    }

    for w in windows:
        pos_mask, neg_mask = mask_by_window[w.name]
        X = masks_to_frame(stay_ids, pos_mask, neg_mask)
        df_w = base.copy()
        for j, col in enumerate(feature_cols):
            df_w[col] = X[:, j]

        for task_name, label_col in tasks.items():
            for model_name in models:
                metrics = _train_eval_predefined(df_w, feature_cols, label_col, model_name)
                row = {
                    "window": w.name,
                    "task": task_name,
                    "model": model_name,
                    "n_samples": metrics["n_samples"],
                    "positive_rate": metrics["positive_rate"],
                    "cv_auroc_mean": metrics["cv_auroc_mean"],
                    "cv_auroc_std": metrics["cv_auroc_std"],
                    "cv_auprc_mean": metrics["cv_auprc_mean"],
                    "cv_auprc_std": metrics["cv_auprc_std"],
                    "test_auroc": metrics["test_auroc"],
                    "test_auprc": metrics["test_auprc"],
                }
                results_rows.append(row)
                payload["results"].append({**row, "fold_details": metrics["fold_details"]})

    out_df = pd.DataFrame(results_rows)
    out_df.to_csv(OUTPUT_CSV, index=False)
    OUTPUT_JSON.write_text(json.dumps(payload, indent=2, ensure_ascii=True))

    print(f"Saved: {OUTPUT_CSV}")
    print(f"Saved: {OUTPUT_JSON}")


if __name__ == "__main__":
    main()
